Implement --vt changing through vnc passthrough
Signed-off-by: Yury Tsarev <ytsarev@suse.com>

diff --git a/suseviclient b/suseviclient
--- a/suseviclient
+++ b/suseviclient
@@ -25,8 +25,10 @@
 
 # end of config section
 
+PATH=.:$PATH
+
 version() {
-  echo "1.0.0"
+  echo "1.1.0"
 }
 
 # setting SSH Control Master
@@ -360,6 +362,7 @@ Generic management:
 --showvncport <vmid> Print VNC port assigned to specified VM
 --addvnc <vmid> Add VNC support to an existing VM ( guest need to be restarted to take effect)
 --remove or --delete <vmid> Delete VM
+\$vmid --vt \$number Switch vt on virtual machine
 
 Snapshot management:
 --------------------
@@ -410,6 +413,7 @@ apikey=\"studioapikey\"
 studioserver=\"istudio.suse.de\"
 
 All specified directives in config file are easily overridable by the related command control option.
+
 
 Help and version:
 -----------------
@@ -542,6 +546,13 @@ relpath2vmdkpath(){
     vmdkpath="$(dirname "$relpath")/$vmdkpath"
 }
 
+read_vnc_password(){
+    stty_orig=`stty -g`
+    stty -echo
+    echo "Enter VNC password:"
+    read vncpassword
+    stty $stty_orig
+}
 
 vnc_connect(){
     vncpassword=""
@@ -554,11 +565,7 @@ vnc_connect(){
         output=$(echo "$vncpassword"|vncviewer -autopass -encodings 'hextile zlib copyrect' $esx_server:$vnc_conn_port 2>&1)
         echo $output| egrep -q "Performing standard VNC authentication"
         if [[ $? -eq 0 && $vncpassword = "" ]]; then
-            stty_orig=`stty -g`
-            stty -echo
-            echo "Enter VNC password:"
-            read vncpassword
-            stty $stty_orig
+            read_vnc_password
             output="suseviclient-vncrestart"
             passwd_counter=$(($passwd_counter+1))
         fi
@@ -617,6 +624,11 @@ get_vnc_port(){
     fi
 }
 
+vncrb(){
+  hash suseviclient-vnc.rb 2>/dev/null || { echo >&2 "Keystroke passthrough requires suseviclient-vnc.rb.  Aborting."; exit 1; }
+  vncrb="suseviclient-vnc.rb"
+}
+
 power_on() {
     if [ ! -z $bios_once ]; then
         vmid2datastore $1
@@ -637,11 +649,11 @@ power_on() {
         $ssh root@$esx_server "vim-cmd vmsvc/message $1 $message 2"
     fi
     if [ -n "$autoyast" ];then
-        test -f ./vnc.rb || echo "Can't find vnc.rb, sorry: no autoyast string will be passed"
+        vncrb
         vmid2datastore $1
         vmid2relpath $1
         get_vnc_port
-        ./vnc.rb "$esx_server" "$vnc_conn_port" test "netsetup=dhcp autoyast=$autoyast"
+        $vncrb "$esx_server" "$vnc_conn_port" test "netsetup=dhcp autoyast=$autoyast"
     fi
 }
 
@@ -1105,7 +1117,19 @@ enable_nested_virtualization() {
     fi
 }
 
-eval set -- `getopt -n$0 -a  --longoptions="vncpass: novncpass ds: iso: vmdk: vnc: help status: poweron: poweroff: reset: snapshot: snapshotremove: all revert: clone: remove: delete: addvnc: bios dslist vmfs dsbrowse: snapshotlist: snapname: snapid: apiuser: apikey: appliances buildimage: buildstatus: studio: studioserver: format: export: networks: vswitches nics vswitchadd: vswitchremove: network: mac: autoyast: showvncport: toserver: cores: nested dtc version" "Vhclyn:s:m:d:e:" "$@"` || usage
+change_vt(){
+  vncrb
+  vmid2datastore $1
+  vmid2relpath $1
+  get_vnc_port
+  $vncrb "$esx_server" "$vnc_conn_port" test "vt$2" 2>&1 | grep 'Unable to authenticate' > /dev/null
+  if [ $? -eq 0 ]; then
+    read_vnc_password
+    $vncrb "$esx_server" "$vnc_conn_port" "$vncpassword" "vt$2" 2>&1 | grep -o 'Unable to authenticate'
+  fi
+}
+
+eval set -- `getopt -n$0 -a  --longoptions="vncpass: novncpass ds: iso: vmdk: vnc: help status: poweron: poweroff: reset: snapshot: snapshotremove: all revert: clone: remove: delete: addvnc: bios dslist vmfs dsbrowse: snapshotlist: snapname: snapid: apiuser: apikey: appliances buildimage: buildstatus: studio: studioserver: format: export: networks: vswitches nics vswitchadd: vswitchremove: network: mac: autoyast: showvncport: toserver: cores: vt: nested dtc version" "Vhclyn:s:m:d:e:" "$@"` || usage
 [ $# -eq 0 ] && usage
 
 while [ $# -gt 0 ]; do
@@ -1149,30 +1173,33 @@ while [ $# -gt 0 ]; do
         --studio) studio="$2";shift;;
         --studioserver) studioserver="$2";shift;;
         --ds) datastore="$2";shift;;
-         --format) format="$2";shift;;
-         --clone) clone_id="$2";shift;;
-         --export) export_id="$2";shift;local_export_dir="$3";shift;;
-         --vswitches) vswitcheslist="1";shift;;
-         --nics) niclist="1";shift;;
-         --networks) networks_id="$2";shift;;
-         --vswitchadd) vswitch_add_name="$2";shift;;
-         --vswitchremove) vswitch_remove_name="$2";shift;;
-         --network) network_name="$2";shift;;
-         --mac) mac="$2";shift;;
-         --autoyast) autoyast="$2";shift;;
-         --showvncport) showvncport_vmid="$2";shift;;
-         --toserver) to_server="$2";shift;;
-         --cores) cores="$2";shift;;
-         --nested) nested="1";;
-         --dtc) deploy_through_client="yes";;
-         -h|--help) usage; exit ;;
-         -V|--version) version; exit ;;
-         --) shift;break;;
-         -*) usage;;
-         *) break;;
+        --format) format="$2";shift;;
+        --clone) clone_id="$2";shift;;
+        --export) export_id="$2";shift;local_export_dir="$3";shift;;
+        --vswitches) vswitcheslist="1";shift;;
+        --nics) niclist="1";shift;;
+        --networks) networks_id="$2";shift;;
+        --vswitchadd) vswitch_add_name="$2";shift;;
+        --vswitchremove) vswitch_remove_name="$2";shift;;
+        --network) network_name="$2";shift;;
+        --mac) mac="$2";shift;;
+        --autoyast) autoyast="$2";shift;;
+        --showvncport) showvncport_vmid="$2";shift;;
+        --toserver) to_server="$2";shift;;
+        --cores) cores="$2";shift;;
+        --vt) vt="$2";shift;;
+        --nested) nested="1";;
+        --dtc) deploy_through_client="yes";;
+        -h|--help) usage; exit ;;
+        -V|--version) version; exit ;;
+        --) shift;break;;
+        -*) usage;;
+        *) break;;
      esac
      shift
 done
+
+vmid="$1"
 
 [ ! -z $esx_server ] && control_master
 
@@ -1371,6 +1398,12 @@ fi
 
 if [ -n "$vswitch_remove_name" ]; then
     vswitchremove $vswitch_remove_name
+    cleanup
+fi
+
+#vnc
+if [[ -n "$vmid" && -n "$vt" ]]; then
+    change_vt $vmid $vt
     cleanup
 fi
 
